<h2>Bienvenidos</h2>
<p>-Aprovechando la oportunidad que nos brinda, presentamos ante usted  nuestra compañía: <br>
<b>PROYECTOS ESPACIOS + DISEÑO y PLANEACIÓN S.A DE C.V.</b></p>
<p>

<br>
-Somos una empresa dedicada a brindarle un servicio de calidad y un alto nivel en<b> ingenierías, arquitectura y construcción</b>.
</p>






<br>
<br>
<p align="center">
<img src="images/02.jpg" title="Proyectos Espacios" align="center" width="380" height="250" border="0">
</p>

<br></br>
<p align="center">
<img src="images/ima1.jpg" title="Proyectos Espacios" align="center" width="390" height="200" border="0">
</p>



<br></br>
<br></br>
<br></br>
<br></br>
<br></br>


