<h2>Bienvenido al blog de noticias</h2>

<br></br>
<h1>-Nuevo portal web</h1>
<p>Para tener un trato más directo personalizado Proyectos Espacios </p>
<p>pone en línea su nuevo portal web.</p>



<br></br>
<h1>-Curso y seminarios</h1>
<p>Curso sobre instalaciones farmacéuticas concluido con éxito.</p>





<br></br>
<h1>-¿Que es la arquitectura?</h1>
<p>
<p>Un breve video que define lo que es la arquitectura</p>
<iframe width="420" height="315" src="http://www.youtube.com/embed/7jXqlEzLVCA" frameborder="0" allowfullscreen></iframe>


<br></br>
<br></br>
<br></br>

<br></br>
<br></br>
<br></br>



