<p align="center"><b><font size="5px" color="#58ACFA">
RESUMEN PROFESIONAL EN LA INSDUSTRIA
</font></b></p>
<p><h3>-Arquitecto: Miguel Ángel Ramírez Bautista</h3></p>
<br>
<p>-Trayectoria  de  17 años en la industria de la construcción, proyectando,</p>
<p>ejecutando y administrando proyectos, obra civil e instalaciones de servicio y críticas,</p>
<p>así como mantenimiento  y Limpieza de inmuebles en el ramo industrial:<br></br><b> Farmacéutico, Farmoquimica, Cosmética Y Alimenticia.</b></p>

<br></br>
<p>-También impartiendo seminarios, cursos y entrenamiento de alto nivel empresarial en</p>
<p>los temas construcción, diseño y calificación de planta farmacéuticas.</p>
<br></br>
<p>-Como solventar requerimientos de la autoridad en el ámbito de obras y giros mercantiles</p>
<br>
<p align="center">
<img src="images/ceo.jpg">
</p>


<br></br>
<br></br>
