<p align="center"><b><font size="5px" color="#58ACFA">
PRINCIPALES CLIENTES Y PROYECTOS: 
</font></b></p>


<h3>TEVA PHARMACEUTICALS MEXICO planta Xochimilco (Arq. José  A. Escobedo)</h3>

-Diseño y Construcción de comedor <br><br>
-Diseño y construcción de Cimentación para equipos de HVAC<br><br>
-Ampliación de planta de inyectables y sólidos oncológicos<br><br>
-Diseño y construcción de planta de hormonales en Xochimilco D.F.<br><br>
-Diseño y construcción de área aséptica inyectables farma <br><br>
-Gestoría y regularización ante la delegación.

<!-- ---><br><br><br>


<h3>COSBEL LOREAL S.A DE C.V (Ing. Hugo Serrano)</h3>
-Proyecto ejecutivo anden de carga y descarga<br><br>
-Proyecto ejecutivo cimentación tanques texapón<br><br>
-Proyecto ejecutivo nuevo sistema de agua de enfriamiento<br><br>
-Diseño y construcción de nuevas oficinas isis<br><br>
-Ingenierías eléctricas y contraincendios de oficinas isis <br><br>
-Gestorías de regularización ante la delegación Xochimilco<br><br>
-Ejecución de estudio de mecánica de suelos<br><br>
- Firma de D.R.O. PARA VoBo de seguridad y operación de planta Xochimilco.<br><br>
- Construcción de cuarto de maquinas y bombas vs incendio.

<!-- ---><br><br><br>


<h3>CENTREX LOREAL (Ing. Juan Benito Mata)</h3>
- Mantenimiento y bacheos epoxicos de centros de distribución<br><br>
- Remodelación comedor<br><br>
- Mantenimiento general almacenes.<br><br>
- Diseño de Layout y ejecución de proyecto Área de emplayadoras.<br><br>
- Diseño e instalación de sistema de extracción comedor.<br><br>
- Diseño y construcción de nuevas casetas de vigilancia

<!-- --><br><br><br>

<h3>LABORATORIOS RUSEK( Ing. Ricardo Carpio)</h3>

     - Remodelación en área de óvulos <br><br>
     - Mantenimiento área de acondicionamiento<br><br>

<!-- --><br><br><br>

<h3>MEGAFARMA( Ing. Martín Hernández)</h3>
- Análisis estructural y reparación de almacenes de materias primas<br><br>
- Remodelación de oficinas corporativas<br><br>
- Mantenimiento general de inmuebles

<!-- --><br><br><br>

<h3>DIMEFAR   S.A. DE C.V.( Lic. Rogelio Lara)</h3>

- Diseño y remodelación de oficinas<br><br>
- Diseño y construcción de almacén de producto terminado<br><br>


<!-- --><br><br><br>

<h3>HIDALMEX S.A. DE C.V.(ING. ROBERTO SANCHEZ)</h3>

- colocación de nuevos pisos epoxico en aéreas de producción <br><br>
- colocación de acabados sanitarios en muros y plafones en aéreas de cámara fría y producción..<br><br>
