
<div id="fichas">
<a href="#"  rel="1" class="button" ><img border="0" src="images/ficha1.png" width="200" height="75" style="position:relative;  top:-45px;" ></a>
<a href="#"  rel="3" class="button" ><img border="0" src="images/ficha3.png" width="200" height="75" style="position:relative; top:-98px;" ></a>
<a href="#"  rel="4" class="button" ><img border="0" src="images/ficha4.png" width="200" height="75" style="position:relative; top:-147px;" ></a>
<a href="#"  rel="5" class="button" ><img border="0" src="images/ficha5.png" width="200" height="75" style="position:relative; top:-195px;" ></a>
</div>