
<a href="contacto.php" ><img align="center" title="Contacto" src="images/pic3.gif"  border="0"  style="position:relative; z-index:2; top:60px; left:320px; " ></a>
<a href="mapsite.php" ><img align="center" title="Mapa del sitio" src="images/pic2.gif"  border="0"  style="position:relative; z-index:2;  top:60px;left:350px; "  ></a>
<a href="index.php" ><img align="center" title="Inicio" src="images/pic1.gif"  border="0"  style="position:relative; z-index:2; top:60px; left:380px; " ></a>