<p align="center"><b><font size="5px" color="#58ACFA">
	OBRAS EN DESARROLLO.
</font></b></p>
<br>

<p>-	Análisis estructural de naves  (loreal xochimilco 70%)</p>
<p>-	Diseño, construcción de enmallado para área de facturación célula 2 ( CENTREX 95% )</p>
<p>-	Mantenimiento y ampliación de área de semisólidos ( RUSEK 95%)</p>
<p>-	Diseño y proyecto ejecutivo de esclusas de seguridad (CENTREX 15%)</p>
<p>-	Diseño y obra civil de fosas de homogenización  e inactivación (HIDALMEX 10%)</p>


<br>
<p align="center">
<img src="images/construccion.jpg">
</p>