<p align="center"><b><font size="5px" color="#58ACFA">
SERVICIOS
</font></b></p>
<h3>DISEÑO:</h3>

-	Analizamos sus requerimientos ( Criterios de Diseño)<br></br>

-	Verificamos que cumplan con normas y reglamentos.<br></br>

-	Realizamos el diseño de lay out<br></br>

-	Realizamos Ingeniería Básica y de detalle de  cada especialidad.<br></br>






<h3>OBRA CIVIL</h3>
-	Desarrollamos excavaciones y cimentaciones<br></br>
-	Construcción de Estructuras metálicas y en concreto<br></br>
-	Construcción de obra negra<br></br>
-	Construcción de áreas Sanitarias, acabados PVC Y EPOXICO<br></br>
-	Construcción de áreas de apoyo ( Laboratorio Q.C., Comedor, Almacenes etc.)<br></br>


<h3>OBRA ESTRUCTURAL</h3>
-	Desarrollamos Diseño y calculo estructural<br></br>
-	Firmas de D.R.O. y Corresponsables.<br></br>


<h3>OBRA ELECTRICA</h3>
-	Desarrollamos el Diseño<br></br>
-	Instalación de líneas de fuerza e iluminación<br></br>
-	Instalación de control<br></br>
-	 Venta y Montaje de equipos de Fuerza<br></br>


<h3>OBRA MECANICA</h3>
-	Desarrollamos Diseño<br></br>
-	Instalación de líneas de servicio<br></br>


<h3>SISTEMAS CRITICOS</h3>
-	Desarrollamos Diseño<br></br>
-	Instalación de Ductos UMAS y Sistemas de extracción.<br></br>
-	Instalación de Líneas de calentamiento y enfriamiento.<br></br>


<h3>TRAMITES DE LICENCIAS Y GESTORIAS</h3>
-	Obtención de manifestaciones de construcción.<br></br>
-	Obtención VoBo de seguridad y Operación.<br></br>
-	Obtención de Certificado  Seguridad Estructural.<br></br>
-	Obtención de Certificado de uso de suelo.<br></br>
-	Firmas de peritos en Instalaciones, Estructuras, Protección Civil, Diseño Arquitectónico,<br></br>

