<h1>Mapa del sitio</h1>
<p>-Inicio <a href="index.php">--></a>  </p>
<p>-Contacto <a href="contacto.php">--></a></p>
<p>-Galería <a href="galeria.php">--></a></p>
<p>-Mapa del sitio <a href="mapsite.php">--></a></p>

<br></br>
<p><b>©PROYECTOS ESPACIOS + DISEÑO Y PLANEACIÓN 2013.</b></p>
<p>-Todos los derechos reservados. México-DF.</p>

<p>-Se prohíbe al Usuario utilizar www.paginaweb.com para propósitos ilegales, inmorales, obscenos o prohibidos.
Todas las imágenes, logotipos y enlaces pertenecen a Proyectos Espacios, o cuentan con sus respectivos derechos legales.

<p>-Portal web diseñado por: Lions</p>

<p>-Diseñado para los navegadores:</p>
<br></br>

<p align="center">
<img src="images/exp.png" align="center" width="180" height="70" style="position:relative; top:20px;" >
</p>


